Style/ModuleFunction:
  Exclude:
    - bin/alpaca
Style/ClassVars:
  Exclude:
    - lib/alpaca/configuration.rb
AllCops:
  Exclude:
    - vendor/**/*
Style/GlobalVars:
  Exclude:
    - lib/alpaca/tools/console_tool.rb